# SPDX-FileCopyrightText: 2026 Yiannis Papadopoulos <giannis.papadopoulos@gmail.com>
# SPDX-License-Identifier: MIT

[project]
name = "vauxhall"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "paho-mqtt>=2.0.0",
    "pyperclip>=1.8.2",
    "pyloid>=0.1.0",
    "PyYAML>=6.0.0",
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I"]
