# SPDX-FileCopyrightText: 2026 Yiannis Papadopoulos <giannis.papadopoulos@gmail.com>
# SPDX-License-Identifier: MIT

"""Installation utility for Vauxhall Gemini CLI hooks."""

import sys
from pathlib import Path
from typing import Any

from vauxhall.hooks import common
from vauxhall.hooks.common import setup_venv

HOOK_MODULE = "vauxhall.hooks.gemini.telemetry_hook"
HOOK_CONFIGS = {
    "BeforeAgent": {
        "name": "vauxhall-thinking",
        "description": "Vauxhall telemetry for Gemini thinking state",
    },
    "AfterAgent": {
        "name": "vauxhall-idle",
        "description": "Vauxhall telemetry for Gemini idle state",
    },
    "SessionEnd": {
        "name": "vauxhall-session-end",
        "description": "Vauxhall telemetry for Gemini session end",
    },
    "BeforeTool": {
        "name": "vauxhall-acting",
        "description": "Vauxhall telemetry for Gemini tool execution",
    },
    "AfterTool": {
        "name": "vauxhall-done",
        "description": "Vauxhall telemetry for Gemini tool completion",
    },
    "AfterModel": {
        "name": "vauxhall-model",
        "description": "Vauxhall telemetry for Gemini model completion",
    },
    "Notification": {
        "name": "vauxhall-waiting",
        "description": "Vauxhall telemetry for Gemini waiting for input",
    },
}
# Hook-system options that older Gemini CLI releases keep beside event entries.
_HOOK_OPTION_KEYS = frozenset({"enabled", "disabled", "notifications"})
# Script path used by handlers from installers that ran the hook from a checkout.
_LEGACY_HOOK_SCRIPT = "/hooks/gemini/telemetry_hook.py"


def build_hook_command(venv_python: Path) -> str:
    """Build a platform-appropriate command for the Gemini hook."""
    return common.build_hook_command(venv_python, HOOK_MODULE)


def load_settings(settings_path: Path) -> dict[str, Any]:
    """Back up, validate, and load existing Gemini settings.

    Args:
        settings_path: Path to the settings.json file.

    Returns:
        The existing valid settings, or an empty dictionary when absent.
    """
    return common.load_hook_settings(settings_path, "Gemini", _HOOK_OPTION_KEYS)


def _is_vauxhall_handler(handler: object) -> bool:
    """Return whether a handler was generated by a Vauxhall Gemini installer."""
    if common.is_hook_handler(handler, HOOK_MODULE):
        return True
    if not isinstance(handler, dict):
        return False
    command = handler.get("command")
    owned_names = {config["name"] for config in HOOK_CONFIGS.values()}
    return (
        handler.get("name") in owned_names
        and isinstance(command, str)
        and command.replace("\\", "/").endswith(_LEGACY_HOOK_SCRIPT)
    )


def purge_vauxhall_hooks(settings: dict[str, Any]) -> None:
    """Remove previously installed Vauxhall Gemini command handlers.

    Args:
        settings: Gemini settings to modify.
    """
    common.purge_hook_handlers(settings, _is_vauxhall_handler, _HOOK_OPTION_KEYS)


def register_hook(
    settings: dict[str, Any], event: str, hook_config: dict[str, str], command: str
) -> None:
    """Register the Vauxhall command handler for one Gemini event.

    Args:
        settings: Gemini settings to modify.
        event: The hook event name (e.g., BeforeAgent).
        hook_config: Dictionary with hook name and description.
        command: The command to execute for the hook.
    """
    handler = {
        "name": hook_config["name"],
        "type": "command",
        "command": command,
        "description": hook_config["description"],
    }
    common.register_hook_handler(settings, event, handler)


def install() -> None:
    """Install Vauxhall telemetry hooks into the current Gemini workspace."""
    print("Vauxhall Gemini Hook Installer")
    print("------------------------------")

    cwd = Path.cwd()
    venv_dir = cwd / ".vauxhall-venv"
    target_settings = cwd / ".gemini" / "settings.json"
    try:
        settings = load_settings(target_settings)
    except (TypeError, ValueError) as error:
        print(f"Error: {error}")
        sys.exit(1)

    venv_python = setup_venv(venv_dir)
    purge_vauxhall_hooks(settings)

    hook_command = build_hook_command(venv_python.absolute())
    for event, config in HOOK_CONFIGS.items():
        register_hook(settings, event, config, hook_command)
        print(f"Registered hook for: {event}")

    try:
        common.write_json_atomically(target_settings, settings)
    except Exception as error:
        print(f"Error saving settings: {error}")
        sys.exit(1)

    print(f"\nSuccess! Hooks installed successfully in {target_settings}")
    print(f"Venv created at {venv_dir}")
    print("You can now monitor this workspace in the Vauxhall Dashboard.")


if __name__ == "__main__":
    install()
